/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AESGCMJni4 */

#ifndef _Included_AESGCMJni4
#define _Included_AESGCMJni4
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AESGCMJni4
 * Method:    doEncryption
 * Signature: ([B[B[B[B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tuttlen_aesgcm_android_AESGCMJni4_doEncryption
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     AESGCMJni4
 * Method:    doDecryption
 * Signature: ([B[B[B[B[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tuttlen_aesgcm_android_AESGCMJni4_doDecryption
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
